{
 "title": "PonyPlace",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Pixels/minute (stacked, 5 minute average)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_bin('$__interval', timestamp, '2022-01-01 00:00:00') as time,\r\n  template,\r\n  -- json::json->>'source' as source,\r\n  count(*)/5 as rate\r\nfrom placements\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time, template --, json::json->>'source'\r\norder by time"
    }
   ]
  },
  {
   "title": "Completion (1 minute average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_bin('$__interval', timestamp, '2022-01-01 00:00:00') as time,\r\n  template,\r\n  avg((nCisPixels - diff_length) / nCisPixels) as completion\r\nfrom (\r\nSELECT\r\n  \"timestamp\",\r\n  json::json->>'template' as template,\r\n  cast(json::json->>'correctPixels' as numeric) as nCisPixels,\r\n  cast(json::json->>'totalPixels' as numeric) as diff_length\r\nFROM others\r\nWHERE event = 'status') as sq\r\nWHERE $__timeFilter(timestamp) and nCisPixels != 0\r\ngroup by time, sq.template\r\norder by time;"
    }
   ]
  },
  {
   "title": "Client error rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_bin('$__interval', timestamp, '2022-01-01 00:00:00') as time,\r\n  json::json->>'message' as error,\r\n  count(*)\r\nFROM others\r\nWHERE event = 'error' and $__timeFilter(timestamp)\r\ngroup by time, error\r\norder by time;"
    }
   ]
  }
 ]
}